POST http://localhost:7000/api/clientes
Content-Type: application/json

{
    "nome": "Vinícius",
    "cpf": "12345678955",
    "email": "vinicius@example1.com",
    "celular": "15349522226",
    "genero": "Masculino",
    "senha": "84631g",
    "confirmarSenha": "84631g"
    
}


###
GET http://localhost:7000/api/clientes


###
GET http://localhost:7000/api/clientes/68100b7830d782aee2f82be5

###
DELETE http://localhost:7000/api/clientes/68100a808fc9840df84bdbcf

###
PUT http://localhost:7000/api/clientes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjYzMGJlMTJhODhjMzNkMmQ3ZDdmMyIsImlhdCI6MTc0NzM0MDQxMSwiZXhwIjoxNzQ3NDI2ODExfQ.eiwi3EqhG3ThLh6IzHD4S5DziSNBM0viLY5et_-otIc

{
    "email": "vinicius@example1.com",
    "genero": "Feminino"
}

###
POST http://localhost:7000/api/clientes/login
Content-Type: application/json

{
    "email": "babu@b.com",
    "senha": "123321c"
}

###
POST http://localhost:7000/api/feirantes
Content-Type: application/json

{
    "nome": "feira privada",
    "cpf_cnpj": "12520319745236",
    "email": "cba@arc.com",
    "celular": "12322112369",
    "genero": "Metamorfo",
    "endereco": "Rua das Flores",
    "numeroCasa": 123,
    "bairro": "Jardim das Rosas",
    "cidade": "São Paulo",
    "uf": "SP",
    "senha": "senhaInsegura123",
    "confirmarSenha": "senhaInsegura123"
}

###
GET http://localhost:7000/api/feirantes

###
GET http://localhost:7000/api/feirantes/
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzBkNjg5YjA5ZDc1YWQxODM5MDljZCIsImlhdCI6MTc0ODAzMjcxMiwiZXhwIjoxNzQ4MTE5MTEyfQ.ZQFvY2-y-6o7nQL_3pLc7gW2cv4f444L9MONF76xDYU"

###
DELETE http://localhost:7000/api/feirantes/681018dd01c94c3f565ea2c0

###
PUT http://localhost:7000/api/feirantes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWU1YzA4NWQ3OWY1MGE3MTc2ZTExMSIsImlhdCI6MTc0NzM2NjQ4MiwiZXhwIjoxNzQ3NDUyODgyfQ.kNtVIIvxW8O6qC5QmeCqELuFmALJ65aohY2ILwxkolg

{
    "celular": "21995548674",
    "genero": "Transformer",
    "cep": "15264896",
    "endereco": "Rua das garças",
    "numeroCasa": 123,
    "bairro": "Itauna",
    "cidade": "Saquarema",
    "uf": "rj"
}

###
POST http://localhost:7000/api/feirantes/login
Content-Type: application/json

{
    "email": "maraba@m.com",
    "senha": "1234n6"
}

###
POST http://localhost:7000/api/produtos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzBkNjg5YjA5ZDc1YWQxODM5MDljZCIsImlhdCI6MTc0ODM5MDg0OCwiZXhwIjoxNzQ4NDc3MjQ4fQ.p3TlK1WqVQm0rqq4JhbLE8cM3rdAzHVbkF_ZACFqEY4

{
    "nome": "Emugel",
    "categoria": "68102a2e7752426bddaa05ab",
    "descricao": "Fruta meio verde,  meio amarela",
    "preco": 7.90,
    "peso": 0.5,
    "quantidade": 5,
    "imagem": "https://www.naturaldaterra.com.br/_next/image?url=https%3A%2F%2Fnaturalterra.vtexassets.com%2Farquivos%2Fids%2F165417%2FPera-Williams-Unidade.jpg%3Fv%3D638671094105730000&w=1440&q=75",
    "status": "Ativo"
}

###
GET http://localhost:7000/api/produtos

###
GET http://localhost:7000/api/produtos/6813a1bb11865d4325d46c6e

###
DELETE http://localhost:7000/api/produtos/6813a57efa0399d36ae3a24a

###
PUT http://localhost:7000/api/produtos/6813a62d8eb1ca17c581eb04
Content-Type: application/json

{
    "nome": "Pera",
    "categoria": "68102a2e7752426bddaa05a9",
    "descricao": "Fruta meio verde,  meio amarela",
    "preco": 10.90,
    "peso": 0.59,
    "imagem": "https://www.naturaldaterra.com.br/_next/image?url=https%3A%2F%2Fnaturalterra.vtexassets.com%2Farquivos%2Fids%2F165417%2FPera-Williams-Unidade.jpg%3Fv%3D638671094105730000&w=1440&q=75",
    "status": "Inativo"
}

###
POST http://localhost:7000/api/enderecoCliente
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWQ0ZDZkYzE0NjNmY2FlOWFkYWNkNSIsImlhdCI6MTc0NzA5NDM1MywiZXhwIjoxNzQ3MTgwNzUzfQ.8fSJrhDRqOXo_KPfygXbfTYv8Me2bw3XKL_uLI74HgI

{
    "cep": "28990-967",
    "endereco": "Rua prosopopéia",
    "numeroCasa": 1564,
    "bairro": "Bacaxá",
    "cidade": "Saquarema",
    "uf": "rj",
    "complemento": "casa",
    "referencia": "perto de outra casa"
}

###
GET http://localhost:7000/api/enderecoCliente

###
GET http://localhost:7000/api/enderecoCliente/6813c2f4de3356d89714f65d

###
DELETE http://localhost:7000/api/enderecoCliente/6813c3d9de3356d89714f66f

###
PUT http://localhost:7000/api/enderecoCliente
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MjYzMGJlMTJhODhjMzNkMmQ3ZDdmMyIsImlhdCI6MTc0NzMzNTU3MywiZXhwIjoxNzQ3NDIxOTczfQ.OBNEEWU8MUjxpeYcKXY1__sMONJodnH3_kFxrOmOaZM

{
    "numeroCasa": 11114,
    "bairro": "Bacaxota",
    "cidade": "Saquarema",
    "uf": "rj",
    "complemento": "Loja",
    "referencia": "perto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra lojaperto de outra loja"
}

###
POST http://localhost:7000/api/feirante/descricao
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MWU1YzA4NWQ3OWY1MGE3MTc2ZTExMSIsImlhdCI6MTc0ODE0NTg4MSwiZXhwIjoxNzQ4MjMyMjgxfQ.8CVxpCx0DggpjELKGrMiHLjph3wC2wHf4Bhn6e0Nz9k

{
    "descricao": "dnsfjkcesvfjgseifgbusgvfjksvfyhesuhfihewuifhjkebvsfhvysegfuhyweoidhuegbfyegsfuygeusghfuiegwuifge8wyhafdoiwhuiedghwyhfioweghrdtw7iyrh83wyer893yw8rf",
    "topicos": ["Alimentos orgânicos", "Feira livre", "Produtos frescos"],
    "enderecos": ["Rua das Feiras, 123", "Avenida Central, box 9"],
    "capa": ["https://meusite.com/img1.jpg", "https://meusite.com/img2.jpg"]


}

###
POST http://localhost:7000/api/feirantes/login
Content-Type: application/json

{
    "email": "feira@vaca.com",
    "senha": "palmas1"
}

###
GET http://localhost:7000/api/feirante/descricao